accuracy:
  feedback:
    collection_method: automatic
    enabled: true
    improvement_threshold: 0.1
  model_thresholds:
    minimum_accuracy: 0.7
    preferred_accuracy: 0.85
  tracking:
    enabled: true
    metrics_file: logs/accuracy_metrics.json
cache:
  embedding_cache:
    directory: cache/embeddings
    enabled: true
    max_size: 1GB
  response_cache:
    enabled: true
    max_size: 1000
    ttl: 3600
development:
  debug: false
  dry_run: false
  intermediates_dir: debug/intermediates
  profiling:
    enabled: false
    output_file: debug/profile.stats
  save_intermediates: true
integrations:
  ci:
    enabled: false
    trigger_tests: true
    webhook_url: ''
  git:
    auto_commit: false
    commit_message_template: Generated {peripheral_name} peripheral model
    enabled: false
knowledge_base:
  auto_update:
    check_interval: 86400
    enabled: true
    sources:
    - paths:
      - src/Infrastructure/src/Emulator/Peripherals
      type: git
      url: https://github.com/renode/renode
  indexing:
    chunk_overlap: 200
    chunk_size: 1000
    metadata_extraction: true
  renode_knowledge_dir: renode_knowledge
llm:
  default_provider: openrouter
  max_tokens:
    code_generation: 8192
    default: 8192
    documentation: 8192
  openrouter_api_key: ${OPENROUTER_API_KEY}
  preferences:
    analysis: openrouter/deepseek/deepseek-r1-0528:free
    code_generation: openrouter/deepseek/deepseek-r1-0528:free
    documentation: openrouter/deepseek/deepseek-r1-0528:free
    testing: openrouter/deepseek/deepseek-r1-0528:free
  temperature_defaults:
    analysis: 0.3
    code_generation: 0.1
    documentation: 0.7
    testing: 0.5
logging:
  console:
    colored: true
    enabled: true
  file:
    backup_count: 5
    enabled: true
    max_size: 10MB
    path: logs/generator.log
  level: INFO
  performance:
    log_llm_calls: true
    log_response_times: true
    log_token_usage: true
milvus:
  collections:
    peripheral_docs: pacer_peripheral_documentation
    renode_examples: pacer_renode_code_examples
  embedding_dim: 768
  embedding_model: nomic-embed-text
  embedding_service: ollama
  host: eddge-sv-clarity.sern.mil
  index_params:
    index_type: IVF_FLAT
    metric_type: L2
    nlist: 128
  ollama_endpoint: http://localhost:11434
  ollama_model: nomic-embed-text
  port: 19530
output:
  base_directory: output
  create_project_structure: true
  naming:
    documentation: '{peripheral_name}_README.md'
    implementation: '{peripheral_name}.cs'
    tests: '{peripheral_name}Tests.cs'
    validation_report: '{peripheral_name}_validation.json'
  organize_by_date: true
pipeline:
  parallel:
    enabled: false
    max_workers: 4
  retry:
    backoff_multiplier: 2
    initial_delay: 5
    max_attempts: 3
  timeouts:
    context_gathering: 60
    final_assembly: 30
    implementation: 120
    interface_definition: 60
    test_generation: 90
    todo_generation: 45
security:
  encrypt_api_keys: false
  max_input_length: 100000
  remove_sensitive_data: true
  sanitize_outputs: true
  validate_inputs: true
templates:
  code_style:
    brace_style: next_line
    indent_size: 4
    max_line_length: 120
    use_spaces: true
  peripheral_types:
    adc: ADC
    can: CAN
    dac: DAC
    ethernet: Ethernet
    gpio: GPIO
    i2c: I2C
    spi: SPI
    timer: Timer
    uart: UART
  template_directory: templates
todo:
  complexity_weights:
    analysis: 1.0
    documentation: 1.5
    implementation: 3.0
    interface_design: 1.5
    register_definition: 2.0
    testing: 2.5
    validation: 2.0
  priority_rules:
    critical_keywords:
    - core
    - essential
    - required
    - must
    high_keywords:
    - important
    - should
    - interrupt
    - dma
    low_keywords:
    - nice-to-have
    - future
    - consider
    medium_keywords:
    - feature
    - enhancement
    - optional
  template_directory: todo_templates
validation:
  code_quality:
    check_error_handling: true
    check_logging: true
    check_naming_conventions: true
    check_renode_patterns: true
  schema_directory: validation_schemas
  strict_mode: true
  thresholds:
    max_complexity_score: 50
    min_documentation_score: 70
    min_test_coverage: 80

# Added model configuration section
models:
  deepseek-r1-0528-free:
    provider: openrouter
    model_id: deepseek/deepseek-r1-0528:free
    max_tokens: 8192
    temperature_range: [0.1, 1.0]
    cost_per_1k_tokens: 0.0
    supports_json: true
    supports_functions: false
    supports_system_prompt: true
    rate_limit: 60
    timeout: 120
